### PR TITLE
Update Erlang Custom Attribute Example

### PR DESCRIPTION
**Pull request by aj-foster**
Hello there 👋🏼 

This change updates the Erlang client documentation around custom attributes. It's based on my interpretation of the client source, so please double-check my work.

Thank you for supporting Erlang and Elixir!

### CODE REVIEW

**Comment by zurab-darkly** [comment]
Hi @aj-foster thank you for submitting this PR. It should be working as documented - see [this test](https://github.com/launchdarkly/erlang-server-sdk/blob/39f0d397ab443de333180457d02452561377ea5d/test/ldclient_user_SUITE.erl#L103) - though, as a side note, I think specifying custom properties like that would make it more consistent with the other SDKs.

**Comment by aj-foster** [comment]
Hello again. Thanks for responding. My reasoning for suggesting this change came from the following:

- [`custom_attributes` type](https://github.com/launchdarkly/erlang-server-sdk/blob/master/src/ldclient_user.erl#L30)
- [Definition of `AllCustomAttributes`](https://github.com/launchdarkly/erlang-server-sdk/blob/master/src/ldclient_user.erl#L98)

This might just indicate that I don't understand how custom attributes work in general. :)

**Comment by zurab-darkly** [comment]
@aj-foster no, your understanding seems correct. It's just in current implementation we have [this logic](https://github.com/launchdarkly/erlang-server-sdk/blob/1.0.0-beta4/src/ldclient_user.erl#L140-L169). I'm just suggesting we should officially add the support (and tests) for the way you'd like it to work.

**Comment by zurab-darkly** [comment]
Per above, I've added this feature to our internal backlog. I'm going to close this docs PR for now, but feel free to create an issue in the [SDK repo](https://github.com/launchdarkly/erlang-server-sdk/issues) if you'd like to follow when it's implemented. At that time we'll also update these docs. Thank you for the suggestion.

**Pull request closed without merging**
