### PR TITLE
Refined webhook introduction, added a detailed section on how to develop

### PR DESCRIPTION
**Pull request by ankitjaininfo**
1. Refined the webhook introduction.
2. Refined the testing section to include more details on getting started with webhooks.

### CODE REVIEW

**Comment by mmrj** [comment]
Hi @ankitjaininfo, Thanks for your feedback. We appreciate the suggestion to add additional intro material about webhooks in the overview for this page. Unfortunately, the remainder of your suggestions are not in line with our [style guide](https://github.com/launchdarkly/LaunchDarkly-Docs/blob/main/style-guide.md).

**Comment by ankitjaininfo** [comment]
Hi @mmrj , can you please suggest the corrections needed or what specific style is not followed? I will get this corrected.

**Comment by scribblingfox** [comment]
Hi @ankitjaininfo! Thanks for your continued interest in improving LaunchDarkly's documentation. As a best practice, we avoid figurative and marketing-style language in our docs. Your use of descriptive nouns and adjectives ("freedom," "seamless," "promptly") is not in compliance with our style guide or general industry best practices for technical writing.

Your suggestion for how to modify webhook behavior is a good one, but we're going to reject it. We don't recommend tools that we haven't tested and verified in-house. Your addition of the Beeceptor tool to our recommendations might be useful, but it isn't one we can endorse in the LaunchDarkly docs because we haven't tested it ourselves.

If you want to make further contributions to tech docs that are more likely to be accepted in the future, I would suggest two strategies:

* offer technical improvements to existing docs, and 
* restrict the language in your PR to the 1,000 most frequently used words in English. Check out the [simple English Wikipedia](https://simple.wikipedia.org/wiki/Main_Page) for examples of writing like this.

Thanks again for your contribution!

**Comment by ankitjaininfo** [comment]
I get it. you can close this PR. 😥

**Pull request closed without merging**
